# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "c3eb4c2f235fcd7b1598a046dd4389c3"
name = "Scalable-modal"
handle = "scalable-modal"
application_url = "https://minerals-quest-officials-happens.trycloudflare.com"
embedded = true

[build]
include_config_on_deploy = true
dev_store_url = "artzen-demo.myshopify.com"
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://minerals-quest-officials-happens.trycloudflare.com/auth/callback",
  "https://minerals-quest-officials-happens.trycloudflare.com/auth/shopify/callback",
  "https://minerals-quest-officials-happens.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
